# tomcat server setting
server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true

# Spring boot environment settings
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  data:
    mongodb:
      uri: mongodb+srv://sarangbang:6CgRzV4NG9q5jSaZ@sarangbang.ot70lz2.mongodb.net/Sarangbang_DB?retryWrites=true&w=majority&appName=Sarangbang

# log settings
logging:
  level:
    root: info
#    debug > info > error (정보 출력량) 중 선택하여 개발, 서비스에 맞춰 변경

# 위까지는 spring꺼 아래부터는 팀, 개인의 변수들
app:
  url:
    server-url: http://10.20.34.233:81
    #    server-url: http://210.110.34.211:81
    # 내 ip (와이파이 환경이라 껐다 켤때마다 달라짐)
  dir:
    imgdir: file:///c:/springsm/imgs/
    uploaddir: c:/springsm/imgs/
    logdir: file:///c:/springsm/logs/
    readlogdir: c:/springsm/logs/

  key:
    algo: PBEWithMD5AndDES
    skey: mykey
    papago-id: v7k1xoe7w2
    papago-secret: SQduWXaGdVRX3w7xiC2rK2l4GDL3Q0zsdXegXgy2
